### ISSUE TITLE
Erreur cache clear

### ISSUE THREAD

**Issue by ckanzafluks** [Monrocq/SnowTricks#19]
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  Cannot load Xdebug - it was already loaded
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "KnpPaginatorBundle" from namespace "Knp\Bundle\PaginatorBundle".
!!  Did you forget a "use" statement for another namespace? in /var/www/html/SnowTricks/src/Kernel.php:23
!!  Stack trace:
!!  #0 /var/www/html/SnowTricks/vendor/symfony/http-kernel/Kernel.php(429): App\Kernel->registerBundles()
!!  #1 /var/www/html/SnowTricks/vendor/symfony/http-kernel/Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 /var/www/html/SnowTricks/vendor/symfony/framework-bundle/Console/Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 /var/www/html/SnowTricks/vendor/symfony/framework-bundle/Console/Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 /var/www/html/SnowTricks/vendor/symfony/console/Application.php(149): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Conso in /var/www/html/SnowTricks/src/Kernel.php on line 23

**Comment by Monrocq** [comment]
Bundle Deleted in "details" branch
